# 2.3. Linear Algebra
D2L의 Linear Algebra 장을 PyTorch 기준으로 정리함.
핵심은 스칼라, 벡터, 행렬, 텐서, 합/평균, 내적, 행렬곱, norm이다.

## 0. 기본 설정

PyTorch를 불러오고 현재 환경을 확인

In [1]:
import torch
print("PyTorch version:", torch.__version__)

PyTorch version: 2.11.0+cu128


## 1. 스칼라

스칼라는 숫자 하나를 뜻함. PyTorch는 숫자 하나도 텐서로 만들수 있음

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print("torch.pow(x, y) =", torch.pow(x, y))

print("x =", x)
print("x.shape =", x.shape)
print("x.item() =", x.item())
print("type(x.item()) =", type(x.item()))

tensor(5.)
tensor(1.)
tensor(6.)
tensor(1.5000)
torch.pow(x, y) = tensor(9.)
x = tensor(3.)
x.shape = torch.Size([])
x.item() = 3.0
type(x.item()) = <class 'float'>


## 2. 벡터

벡터는 숫자 여러개가 한줄로 있는 것임. 1차원 텐서라고 생각하면 됨.

In [3]:
x = torch.arange(4, dtype=torch.float32)

print(x)
print("x[3] = ", x[3])
print("x.shape = ", x.shape)
print("x.ndim =", x.ndim) # 몇차원인지 (축 개수)

tensor([0., 1., 2., 3.])
x[3] =  tensor(3.)
x.shape =  torch.Size([4])
x.ndim = 1


## 3. 스칼라와 벡터 연산

In [4]:
a = 2
x = torch.tensor([1,2,3], dtype=torch.float32)
y = torch.tensor([10,20,30], dtype=torch.float32)

print(a * x) # 모든 원소에 a곱함.
print(a * x + y) # 같은 위치에 y더함

tensor([2., 4., 6.])
tensor([12., 24., 36.])


## 4. 행렬

행렬은 2차원 텐서를 말함. 표처럼 생긴 데이터 생각

In [5]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

print(A)
print(A.shape)

print("A[0, 0] =", A[0, 0])
print("A[1, 2] =", A[1, 2])
print("A[0] =", A[0])       # 첫 번째 행
print("A[:, 0] =", A[:, 0]) # 첫 번째 열

print(A.T) # 전치 행렬은 행이랑 열 바꾸는 것
print(A.shape)
print(A.T.shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
torch.Size([5, 4])
A[0, 0] = tensor(0.)
A[1, 2] = tensor(6.)
A[0] = tensor([0., 1., 2., 3.])
A[:, 0] = tensor([ 0.,  4.,  8., 12., 16.])
tensor([[ 0.,  4.,  8., 12., 16.],
        [ 1.,  5.,  9., 13., 17.],
        [ 2.,  6., 10., 14., 18.],
        [ 3.,  7., 11., 15., 19.]])
torch.Size([5, 4])
torch.Size([4, 5])


## 5. 텐서

D2L에서는 백터가 1차 order텐서, 행렬이 2차 order 텐서이고, 더 많은 축을 가진 일반 자료구조를 텐서라고 설명했다.
이미지 데이터는 높이, 너비, 색상 채널 같은 여러축을 가져서 텐서가 중요하다.

In [6]:
X = torch.arange(24, dtype=torch.float32).reshape(2,3,4)  # 큰덩어리 2개 덩아리 안에 3행 4열짜리 작은 덩어리 2개 들어있음. (2,3,4) 3차원 텐서

print("X.shape = ", X.shape)
print(X)

print(X.ndim)   # 3
print(X.numel())  # 24

X.shape =  torch.Size([2, 3, 4])
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
3
24


## 6. 같은 shape끼리 원소별 연산

같은 shape끼리 더하면 결과 shape도 같다.
스칼라를 곱해도 shape은 그대로다.

In [7]:
a = 2
x = torch.ones(3)
y = torch.zeros(3)

print(x)
print(y)
print(a * x)
print (a * x + y)

print(x.shape)
print(y.shape)
print((a * x).shape)
print((a * x + y).shape)


tensor([1., 1., 1.])
tensor([0., 0., 0.])
tensor([2., 2., 2.])
tensor([2., 2., 2.])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])


## 7. 합과 평균

In [8]:
x = torch.ones(3)

print(x)
print(torch.sum(x))
print(x.sum())

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

print(A)
print(A.sum())

print(A.mean())
print(A.sum() / A.numel())

print("A.shape =", A.shape)

print("전체 합 =", A.sum())
print("열 방향으로 합 dim=0 =", A.sum(dim=0))
print("행 방향으로 합 dim=1 =", A.sum(dim=1))

tensor([1., 1., 1.])
tensor(3.)
tensor(3.)
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor(190.)
tensor(9.5000)
tensor(9.5000)
A.shape = torch.Size([5, 4])
전체 합 = tensor(190.)
열 방향으로 합 dim=0 = tensor([40., 45., 50., 55.])
행 방향으로 합 dim=1 = tensor([ 6., 22., 38., 54., 70.])


## 8. 점곱 (dot product)

같은 길이의 두 벡터에서 같은 위치끼리 곱하고 전부 더하는것을 점곱이라고 함 (내적)

In [9]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4)

print(torch.dot(x, y))
print((x * y).sum()) # 점곱

tensor(6.)
tensor(6.)


## 9. 행렬-벡터 곱

In [10]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
x = torch.arange(4, dtype=torch.float32)

print("A.shape =", A.shape) # 5,4
print("x.shape =", x.shape) # 4,

y = torch.matmul(A, x) # A와 x의 행렬곱
print(y) # 안쪽크기 4가 맞아서 가능함 결과는 (5,)
print("y.shape =", y.shape)

A.shape = torch.Size([5, 4])
x.shape = torch.Size([4])
tensor([ 14.,  38.,  62.,  86., 110.])
y.shape = torch.Size([5])


## 10. 행렬-행렬 곱

행렬곱은 행과 열의 점곱임. @는 행렬곱 연산자다.

In [11]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = torch.ones(4, 3)

print("A.shape =", A.shape)
print("B.shape =", B.shape)

C = torch.matmul(A, B)
print(C)
print(C.shape)

A.shape = torch.Size([5, 4])
B.shape = torch.Size([4, 3])
tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])
torch.Size([5, 3])


## 11. norm
norm은 벡터나 행렬의 크기임. D2L에서는 nd.norm사용하는데 최신은 torch.linalg.vector_norm 또는 torch.linalg.matrix_norm를 사용한다고 함.

[https://docs.pytorch.org/docs/2.12/generated/torch.norm.html]
[https://docs.pytorch.org/docs/2.12/generated/torch.linalg.matrix_norm.html]

In [12]:
x = torch.arange(4, dtype=torch.float32) # 벡터의 L2 norm

print(x)
print(torch.linalg.vector_norm(x)) # sqrt(0^2 + 1^2 + 2^2 + 3^2) = sqrt(14)

print(torch.abs(x).sum()) # 벡터의 L1 norm (절대값 합)
print(torch.linalg.vector_norm(x, ord=1))

A = torch.arange(20, dtype=torch.float32).reshape(5, 4) # 행렬의 Frobenius norm (모든 원소의 제곱합의 제곱근)
print(torch.linalg.matrix_norm(A, ord="fro"))

tensor([0., 1., 2., 3.])
tensor(3.7417)
tensor(6.)
tensor(6.)
tensor(49.6991)


## 12. 오늘의 정리

- 스칼라는 숫자 하나이며, PyTorch에서는 0차원 텐서로 표현할 수 있다.
- `torch.tensor(3.0)`은 스칼라 텐서이고, `torch.tensor([3.0])`은 원소가 1개인 1차원 텐서다.
- 벡터는 숫자 여러 개가 한 줄로 있는 1차원 텐서다.
- 행렬은 행과 열을 가진 2차원 텐서다.
- 일반적으로 텐서는 여러 개의 축을 가진 다차원 배열이다.
- `shape`은 텐서의 차원 구조를 나타낸다.
- `ndim`은 텐서가 몇 개의 축을 가지는지 나타낸다.
- `numel()`은 텐서 전체 원소 개수를 반환한다.
- 같은 shape을 가진 텐서끼리는 원소별 연산을 할 수 있다.
- 스칼라와 텐서를 연산하면 스칼라가 모든 원소에 적용된다.
- `sum()`은 원소들의 합을 구한다.
- `mean()`은 원소들의 평균을 구한다.
- `dim=0`은 행 방향으로 내려가며 계산해서 각 열의 결과를 만든다.
- `dim=1`은 열 방향으로 가로질러 계산해서 각 행의 결과를 만든다.
- 점곱(dot product)은 같은 위치의 원소끼리 곱한 뒤 전부 더하는 연산이다.
- 행렬-벡터 곱은 행렬의 각 행과 벡터의 점곱으로 계산된다.
- 행렬-행렬 곱은 왼쪽 행렬의 행과 오른쪽 행렬의 열 사이의 점곱으로 계산된다.
- `torch.matmul()` 또는 `@`를 사용해서 행렬곱을 수행할 수 있다.
- 행렬곱은 안쪽 차원이 맞아야 한다. 예를 들어 `(5, 4) @ (4, 3)`은 가능하고 결과는 `(5, 3)`이다.
- 벡터의 L2 norm은 원소 제곱합의 제곱근이다.
- 벡터의 L1 norm은 원소 절대값의 합이다.
- 행렬의 Frobenius norm은 모든 원소 제곱합의 제곱근이다.
- 딥러닝에서 선형대수는 데이터 표현, 가중치 계산, 행렬곱, 손실 계산의 기본 도구다.
