# 2.1. Data Manipulation

D2L의 Data Manipulation 장을 PyTorch 기준으로 변환해서 학습함.


## 0. 기본 설정

PyTorch를 불러오고 현재 환경을 확인

In [1]:
import torch
print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 2.11.0+cu128
CUDA available: True


## 1. Tensor 만들기

Tensor는 PyTorch에서 데이터를 표현하는 기본 단위입니다.

그냥 배열로 봐도 되지만, 정확히는 shape, dtype, device, 자동미분 정보를 가질 수 있는 다차원 수치 배열입니다. 
shape은 차원 구조, dtype은 원소의 자료형, device는 Tensor가 놓인 위치, numel은 전체 원소 개수입니다.

In [2]:
x = torch.arange(12, dtype=torch.float32)
print(x)

# torch.Size([12])는 원소 12개짜리 1차원 Tensor라는 뜻이다.
print("shape:", x.shape)
print("dtype:", x.dtype)
print("device:", x.device)
print("numel:", x.numel())

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
shape: torch.Size([12])
dtype: torch.float32
device: cpu
numel: 12


## 2. reshape

reshape는 값은 그대로 두고 모양만 바꿉니다. 
전체 원소 개수 12개가 유지되므로 3 x 4처럼 바꿀 수 있음.

In [3]:
X = x.reshape(3, 4)
print(X)
print("X shape:", X.shape)

print(x.reshape(-1, 4)) # -1은 해당 차원을 자동 계산하라는 뜻
print(x.reshape(3, -1)) 

# 전체 원소 개수가 15개가 되어야 하므로 아래 코드는 에러가 남
# x.reshape(5, 3)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
X shape: torch.Size([3, 4])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


## 3. 자주 쓰는 Tensor 생성 함수

zeros는 0으로 채운 Tensor, 
ones는 1로 채운 Tensor, 
randn은 표준정규분포 난수 Tensor를 만듭니다. 

In [4]:
print(torch.zeros((2, 3, 4)))
print(torch.ones((2, 3, 4)))
print(torch.randn(3, 4))

Y = torch.tensor([
    [2.0, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1]
])
print(Y)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[ 0.6940, -0.9440,  0.9591,  0.5924],
        [-0.6979, -2.1943, -0.5126, -0.3922],
        [-0.8154,  0.9512,  0.7212, -1.0248]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


## 4. 요소별 연산

Tensor의 기본 산술 연산은 같은 위치의 원소끼리 수행됩니다. 
*는 행렬 곱이 아니라 요소별 곱이고, torch.exp처럼 함수도 각 원소에 한 번에 적용됩니다.

In [5]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2.0, 2, 2, 2])

print("x:", x)
print("y:", y)
print("x + y:", x + y)
print("x - y:", x - y)
print("x * y:", x * y)
print("x / y:", x / y)
print("x ** y:", x ** y)
print("torch.exp(x):", torch.exp(x))

x: tensor([1., 2., 4., 8.])
y: tensor([2., 2., 2., 2.])
x + y: tensor([ 3.,  4.,  6., 10.])
x - y: tensor([-1.,  0.,  2.,  6.])
x * y: tensor([ 2.,  4.,  8., 16.])
x / y: tensor([0.5000, 1.0000, 2.0000, 4.0000])
x ** y: tensor([ 1.,  4., 16., 64.])
torch.exp(x): tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


## 5. 행렬 곱

요소별 곱은 *, 행렬 곱은 @ 또는 torch.matmul입니다. X는 3 x 4, Y는 3 x 4라서 X @ Y는 불가능하지만,
근데 Y.T를 사용하면 4 x 3이 되어 행렬 곱이 가능합니다.

In [6]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)

Y = torch.tensor([
    [2.0, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1]
])

print("X shape:", X.shape)
print("Y shape:", Y.shape)
print("Y.T shape:", Y.T.shape)

matrix_product = X @ Y.T
print(matrix_product)
print("result shape:", matrix_product.shape)

X shape: torch.Size([3, 4])
Y shape: torch.Size([3, 4])
Y.T shape: torch.Size([4, 3])
tensor([[ 18.,  20.,  10.],
        [ 58.,  60.,  50.],
        [ 98., 100.,  90.]])
result shape: torch.Size([3, 3])


## 6. Tensor 합치기

torch.cat으로 Tensor를 합칩니다. 
dim=0은 행 방향으로 붙이는 것, dim=1은 열 방향으로 붙이는 것입니다.

In [7]:
cat_dim0 = torch.cat((X, Y), dim=0)
print(cat_dim0)
print("dim=0 shape:", cat_dim0.shape)

cat_dim1 = torch.cat((X, Y), dim=1)
print(cat_dim1)
print("dim=1 shape:", cat_dim1.shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
dim=0 shape: torch.Size([6, 4])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])
dim=1 shape: torch.Size([3, 8])


## 7. 비교 연산

비교 연산도 같은 위치의 원소끼리 수행됩니다.
결과는 True/False를 가진 boolean으로 나옵니다.

In [8]:
print("X == Y")
print(X == Y)
print("X < Y")
print(X < Y)
print("X > Y")
print(X > Y)

X == Y
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
X < Y
tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])
X > Y
tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


## 8. 합계와 Python 숫자 변환

X.sum()은 Tensor를 반환하고, item()은 Python 숫자를 반환합니다. 
loss 출력이나 로그 기록에서 item()을 자주 씁니다.

In [9]:
s = X.sum()
print(s)
print(type(s), s)
print(s.item())
print(type(s.item()))

tensor(66.)
<class 'torch.Tensor'> tensor(66.)
66.0
<class 'float'>


## 9. Broadcasting

Broadcasting은 shape이 다른 Tensor끼리도 특정 조건에서 연산할 수 있게 해주는 규칙입니다. 
(3, 1)과 (1, 2)는 (3, 2)로 확장되어 연산됩니다.

In [10]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)

print("a")
print(a)
print("b")
print(b)

result = a + b
print(result)
print("a shape:", a.shape)
print("b shape:", b.shape)
print("result shape:", result.shape)

a
tensor([[0],
        [1],
        [2]])
b
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])
a shape: torch.Size([3, 1])
b shape: torch.Size([1, 2])
result shape: torch.Size([3, 2])


## 10. 3차원 Broadcasting 연습

(3, 1, 1)과 (1, 4, 5)는 broadcasting되어 (3, 4, 5)가 됩니다. 
result[0]은 b + 0, result[1]은 b + 1, result[2]는 b + 2입니다.

In [11]:
a = torch.arange(3).reshape(3, 1, 1)
b = torch.arange(20).reshape(1, 4, 5)

print("a shape:", a.shape)
print("b shape:", b.shape)

result = a + b
print("result shape:", result.shape)

print("result[0]")
print(result[0])
print("result[1]")
print(result[1])
print("result[2]")
print(result[2])

a shape: torch.Size([3, 1, 1])
b shape: torch.Size([1, 4, 5])
result shape: torch.Size([3, 4, 5])
result[0]
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
result[1]
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
result[2]
tensor([[ 2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21]])


## 11. Indexing과 Slicing

indexing과 slicing으로 Tensor 일부에 접근하거나 값을 바꿀 수 있습니다. 
X[-1]은 마지막 행, X[1:3]은 1번째 행부터 2번째 행까지, X[1, 2]는 1행 2열, X[:2, :]는 앞의 두 행 전체입니다.

In [12]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
print(X)

print("X[-1]")
print(X[-1])

print("X[1:3]")
print(X[1:3])

print("X[1, 2]")
print(X[1, 2])

X[1, 2] = 17
print(X)

X[:2, :] = 12
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
X[-1]
tensor([ 8.,  9., 10., 11.])
X[1:3]
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
X[1, 2]
tensor(6.)
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


## 12. NumPy 변환

CPU Tensor는 numpy()로 NumPy 배열로 바꿀 수 있습니다. 
반대로 torch.from_numpy로 NumPy 배열을 Tensor로 바꿀 수 있습니다. 

GPU Tensor는 cpu()로 옮긴 뒤 numpy()를 호출해야 합니다.

In [13]:
A = X.numpy()
print(A)
print(type(A))

B = torch.from_numpy(A)
print(B)
print(type(B))

# GPU Tensor라면 이런 식으로 변환한다.
# X.cpu().numpy()

[[12. 12. 12. 12.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<class 'numpy.ndarray'>
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])
<class 'torch.Tensor'>


## 13. GPU 확인

Tensor를 GPU나 CPU로 옮길 때는 to(device)를 사용합니다. 
CPU Tensor와 GPU Tensor를 섞어 연산하면 에러가 납니다.

In [14]:
print(torch.cuda.is_available())

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
X = X.to(device)
print(X.device)

True
cuda
cuda:0


## 14. 연습문제 풀이 - 연습문제 1

조건문 X == Y를 X < Y, X > Y로 바꿔서 결과를 확인합니다. 세 비교 모두 요소별 비교입니다.

In [15]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)

Y = torch.tensor([
    [2.0, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1]
])

print("X == Y")
print(X == Y)
print("X < Y")
print(X < Y)
print("X > Y")
print(X > Y)

X == Y
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
X < Y
tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])
X > Y
tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


## 14. 연습문제 풀이 - 연습문제 2

3차원 Tensor broadcasting을 확인합니다. 예상 결과 shape은 (3, 4, 5)이고 실제 결과도 같습니다.

In [16]:
a = torch.arange(3).reshape(3, 1, 1)
b = torch.arange(20).reshape(1, 4, 5)

result = a + b

print("a shape:", a.shape)
print("b shape:", b.shape)
print("result shape:", result.shape)
print(result)

a shape: torch.Size([3, 1, 1])
b shape: torch.Size([1, 4, 5])
result shape: torch.Size([3, 4, 5])
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16],
         [17, 18, 19, 20, 21]]])


## 14. 연습문제 풀이 - 연습문제 3

구버전 MXNet 코드 c = nd.dot(a, b.T) + c를 PyTorch로 바꿉니다.

단순 버전은 c = a @ b.T + c입니다.

메모리 효율 버전은 c.addmm_(a, b.T)입니다. addmm_는 c = c + a @ b.T를 in-place로 수행하고, 함수 이름 끝의 _는 PyTorch에서 in-place 연산을 의미합니다. requires_grad=True가 걸린 학습 코드에서는 in-place 연산을 조심해야 합니다.

In [17]:
torch.manual_seed(42)

a = torch.randn(3, 4)
b = torch.randn(5, 4)
c = torch.zeros(3, 5)

c.addmm_(a, b.T)
print(c)

tensor([[-0.0287,  0.1931, -0.2530, -0.2803, -0.3271],
        [-1.5151, -3.7800,  0.9855, -3.4836,  0.9977],
        [-0.0877, -0.0806, -0.1305, -1.3545, -0.1253]])


## 15. 오늘의 정리

- Tensor는 PyTorch에서 데이터를 표현하는 기본 단위다.
- 그냥 배열로 봐도 되지만, 정확히는 shape, dtype, device, 자동미분 정보를 가질 수 있는 다차원 수치 배열이다.
- shape은 차원 구조다.
- numel은 전체 원소 수다.
- reshape는 전체 원소 개수가 유지될 때만 가능하다.
- *는 요소별 곱이다.
- @는 행렬 곱이다.
- broadcasting은 편하지만 shape 버그의 원인이 될 수 있다.
- indexing과 slicing으로 Tensor 일부에 접근할 수 있다.
- Tensor와 NumPy 배열은 서로 변환할 수 있다.
- GPU Tensor는 numpy 변환 전 cpu()로 옮겨야 한다.